baseURL = "https://www.javiertibau.com/"
languageCode = "en-us"
title = "Javier Tibau"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  description = "Associate Professor of Computer Science at Virginia Commonwealth University, with a background in human-computer interaction and building user-centric systems."
  author = "Javier Tibau"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  mainSections = ["projects"]

  [params.profileMode]
    enabled = true
    title = "Javier Tibau"
    subtitle = "Associate Professor of Computer Science at Virginia Commonwealth University."
    imageUrl = "/images/JavierTibau.jpeg"
    imageWidth = 150
    imageHeight = 150
    imageTitle = "Javier Tibau (portrait)"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/jtibau"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/javiertibau"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:javier@javiertibau.com"

[params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"


[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10
#   [[menu.main]]
#     name = "Writing"
#     url = "/posts/"
#     weight = 30
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 40
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true